version: "3.8"

services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - "9090:8082"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: llama3.2:1b
    depends_on:
      - mariadb
      - ollama

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: miola
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data: